### ISSUE TITLE
Error on startup [1.13.2]

### ISSUE THREAD

**Issue by BaneOfSmite** [TheBusyBiscuit/ChestTerminal#10]
Color code also not working properly ![image](https://user-images.githubusercontent.com/23048417/56128031-2ff5d180-5fb1-11e9-9188-a243bdefda14.png)

Error:

[18:59:56 INFO]: [ChestTerminal] Enabling ChestTerminal v1.0*
[18:59:56 ERROR]: Fatal error trying to convert ChestTerminal v1.0:me/mrCookieSlime/ChestTerminal/QuartzDrill.class
org.bukkit.plugin.AuthorNagException: No legacy enum constant for BLACK_STAINED_GLASS_PANE. Did you forget to define api-version: 1.13 in your plugin.yml?
        at org.bukkit.craftbukkit.v1_13_R2.util.Commodore$1$1.visitFieldInsn(Commodore.java:272) ~[patched_1.13.2.jar:git-Paper-620]
        at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2210) ~[patched_1.13.2.jar:git-Paper-620]
        at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1283) ~[patched_1.13.2.jar:git-Paper-620]
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:688) ~[patched_1.13.2.jar:git-Paper-620]
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:400) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.craftbukkit.v1_13_R2.util.Commodore.convert(Commodore.java:173) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.craftbukkit.v1_13_R2.util.CraftMagicNumbers.processClass(CraftMagicNumbers.java:238) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:113) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:199) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[patched_1.13.2.jar:git-Paper-620]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_201]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_201]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_201]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:136) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:199) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[patched_1.13.2.jar:git-Paper-620]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        at me.mrCookieSlime.ChestTerminal.ChestTerminal.onEnable(ChestTerminal.java:46) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-620]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-620]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-620]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-620]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-620]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[patched_1.13.2.jar:git-Paper-620]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
[18:59:56 ERROR]: Fatal error trying to convert ChestTerminal v1.0:me/mrCookieSlime/ChestTerminal/QuartzDrill$1.class
org.bukkit.plugin.AuthorNagException: No legacy enum constant for GRAY_STAINED_GLASS_PANE. Did you forget to define api-version: 1.13 in your plugin.yml?
        at org.bukkit.craftbukkit.v1_13_R2.util.Commodore$1$1.visitFieldInsn(Commodore.java:272) ~[patched_1.13.2.jar:git-Paper-620]
        at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2210) ~[patched_1.13.2.jar:git-Paper-620]
        at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1283) ~[patched_1.13.2.jar:git-Paper-620]
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:688) ~[patched_1.13.2.jar:git-Paper-620]
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:400) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.craftbukkit.v1_13_R2.util.Commodore.convert(Commodore.java:173) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.craftbukkit.v1_13_R2.util.CraftMagicNumbers.processClass(CraftMagicNumbers.java:238) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:113) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:199) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[patched_1.13.2.jar:git-Paper-620]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        at me.mrCookieSlime.ChestTerminal.QuartzDrill.<init>(QuartzDrill.java:37) ~[?:?]
        at me.mrCookieSlime.ChestTerminal.ChestTerminal$1.<init>(ChestTerminal.java:47) ~[?:?]
        at me.mrCookieSlime.ChestTerminal.ChestTerminal.onEnable(ChestTerminal.java:46) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-620]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-620]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-620]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-620]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-620]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[patched_1.13.2.jar:git-Paper-620]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
[18:59:56 ERROR]: Fatal error trying to convert ChestTerminal v1.0:me/mrCookieSlime/ChestTerminal/AccessTerminal.class
org.bukkit.plugin.AuthorNagException: No legacy enum constant for BLACK_STAINED_GLASS_PANE. Did you forget to define api-version: 1.13 in your plugin.yml?
        at org.bukkit.craftbukkit.v1_13_R2.util.Commodore$1$1.visitFieldInsn(Commodore.java:272) ~[patched_1.13.2.jar:git-Paper-620]
        at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2210) ~[patched_1.13.2.jar:git-Paper-620]
        at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1283) ~[patched_1.13.2.jar:git-Paper-620]
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:688) ~[patched_1.13.2.jar:git-Paper-620]
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:400) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.craftbukkit.v1_13_R2.util.Commodore.convert(Commodore.java:173) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.craftbukkit.v1_13_R2.util.CraftMagicNumbers.processClass(CraftMagicNumbers.java:238) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:113) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:199) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[patched_1.13.2.jar:git-Paper-620]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        at me.mrCookieSlime.ChestTerminal.ChestTerminal.onEnable(ChestTerminal.java:66) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-620]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-620]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-620]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-620]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-620]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[patched_1.13.2.jar:git-Paper-620]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
[18:59:56 ERROR]: Fatal error trying to convert ChestTerminal v1.0:me/mrCookieSlime/ChestTerminal/ImportBus.class
org.bukkit.plugin.AuthorNagException: No legacy enum constant for CYAN_STAINED_GLASS_PANE. Did you forget to define api-version: 1.13 in your plugin.yml?
        at org.bukkit.craftbukkit.v1_13_R2.util.Commodore$1$1.visitFieldInsn(Commodore.java:272) ~[patched_1.13.2.jar:git-Paper-620]
        at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2210) ~[patched_1.13.2.jar:git-Paper-620]
        at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1283) ~[patched_1.13.2.jar:git-Paper-620]
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:688) ~[patched_1.13.2.jar:git-Paper-620]
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:400) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.craftbukkit.v1_13_R2.util.Commodore.convert(Commodore.java:173) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.craftbukkit.v1_13_R2.util.CraftMagicNumbers.processClass(CraftMagicNumbers.java:238) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:113) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:199) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[patched_1.13.2.jar:git-Paper-620]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        at me.mrCookieSlime.ChestTerminal.ChestTerminal.onEnable(ChestTerminal.java:70) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-620]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-620]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-620]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-620]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-620]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[patched_1.13.2.jar:git-Paper-620]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
[18:59:56 ERROR]: Fatal error trying to convert ChestTerminal v1.0:me/mrCookieSlime/ChestTerminal/ImportBus$1.class
org.bukkit.plugin.AuthorNagException: No legacy enum constant for WHITE_WOOL. Did you forget to define api-version: 1.13 in your plugin.yml?
        at org.bukkit.craftbukkit.v1_13_R2.util.Commodore$1$1.visitFieldInsn(Commodore.java:272) ~[patched_1.13.2.jar:git-Paper-620]
        at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2210) ~[patched_1.13.2.jar:git-Paper-620]
        at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1283) ~[patched_1.13.2.jar:git-Paper-620]
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:688) ~[patched_1.13.2.jar:git-Paper-620]
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:400) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.craftbukkit.v1_13_R2.util.Commodore.convert(Commodore.java:173) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.craftbukkit.v1_13_R2.util.CraftMagicNumbers.processClass(CraftMagicNumbers.java:238) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:113) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:199) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[patched_1.13.2.jar:git-Paper-620]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        at me.mrCookieSlime.ChestTerminal.ImportBus.<init>(ImportBus.java:30) ~[?:?]
        at me.mrCookieSlime.ChestTerminal.ChestTerminal.onEnable(ChestTerminal.java:70) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-620]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-620]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-620]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-620]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-620]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[patched_1.13.2.jar:git-Paper-620]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
[18:59:56 ERROR]: Fatal error trying to convert ChestTerminal v1.0:me/mrCookieSlime/ChestTerminal/ExportBus.class
org.bukkit.plugin.AuthorNagException: No legacy enum constant for CYAN_STAINED_GLASS_PANE. Did you forget to define api-version: 1.13 in your plugin.yml?
        at org.bukkit.craftbukkit.v1_13_R2.util.Commodore$1$1.visitFieldInsn(Commodore.java:272) ~[patched_1.13.2.jar:git-Paper-620]
        at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2210) ~[patched_1.13.2.jar:git-Paper-620]
        at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1283) ~[patched_1.13.2.jar:git-Paper-620]
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:688) ~[patched_1.13.2.jar:git-Paper-620]
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:400) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.craftbukkit.v1_13_R2.util.Commodore.convert(Commodore.java:173) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.craftbukkit.v1_13_R2.util.CraftMagicNumbers.processClass(CraftMagicNumbers.java:238) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:113) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:199) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[patched_1.13.2.jar:git-Paper-620]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        at me.mrCookieSlime.ChestTerminal.ChestTerminal.onEnable(ChestTerminal.java:74) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-620]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-620]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-620]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-620]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-620]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-620]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[patched_1.13.2.jar:git-Paper-620]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

**Comment by TheBusyBiscuit** [comment]
You are using a very old version of ChestTerminal, one that does not support 1.13

Check the Readme for a link to all builds.

**Comment by BaneOfSmite** [comment]
it was ChestTerminal - #3

**Comment by TheBusyBiscuit** [comment]
The error shows a different version though.
Anyway, try out Build no. 4

**Comment by BaneOfSmite** [comment]
Thanks, build 4 fixed it ^~^
